version: "3"

services:
  garlicoind:
    image: ghcr.io/orangedrangon/garlicoind:latest
    restart: unless-stopped
    env_file: vars.env
    volumes:
      - ./garlicoind:/var/lib/garlicoind

  broadcaster:
    build: ./broadcaster
    restart: unless-stopped
    env_file: vars.env
    ports:
      - 8000:8000
    depends_on:
      - garlicoind
