version: "3"

services:
  garlicoind:
    image: ghcr.io/orangedrangon/garlicoind:latest
    restart: unless-stopped
    env_file: vars.env
    volumes:
      # point path before the colon to where the garlicoin data is
      - ./garlicoind:/var/lib/garlicoind

  broadcaster:
    build: ./broadcaster
    restart: unless-stopped
    env_file: vars.env
    ports:
      # change the port before the colon the change what port it is bound on the host machine
      - 8000:8000
    depends_on:
      - garlicoind
